apiVersion: v1
kind: Secret
metadata:
  name: uppi-secrets
  namespace: uppi
type: Opaque
stringData:
  # Application
  APP_KEY: "base64:your-32-char-key"
  
  # Database
  DB_USERNAME: "database-username"
  DB_PASSWORD: "database-password"
  
  # Mail
  MAIL_USERNAME: "mailgun-username"
  MAIL_PASSWORD: "mailgun-password"
  MAIL_FROM_ADDRESS: "no-reply@uppi.dev"
  MAILGUN_DOMAIN: "mail.uppi.dev"
  MAILGUN_SECRET: "your-mailgun-secret"
  
  # AWS
  AWS_ACCESS_KEY_ID: "your-aws-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret"
  AWS_BUCKET: "your-bucket-name"
  
  # Pusher/WebSockets
  PUSHER_APP_ID: "your-pusher-app-id"
  PUSHER_APP_KEY: "your-pusher-key"
  PUSHER_APP_SECRET: "your-pusher-secret"
  
  # Other Services
  STRIPE_KEY: "your-stripe-key"
  STRIPE_SECRET: "your-stripe-secret"
  STRIPE_WEBHOOK_SECRET: "your-stripe-webhook-secret" 