name: Tests
on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}
          restore-keys: composer-
          retention-days: 7

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      # Cache Node.js dependencies
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json') }}
          restore-keys: node-modules-
          retention-days: 7

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Create .env file
        run: cp .env.example .env

      - name: Create database
        run: touch database/database.sqlite

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install node dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Generate key
        run: php artisan key:generate --force

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: ./vendor/bin/pest --ci --parallel